[package]
name = "csgoempire"
version = "0.1.0"
authors = ["WeirdPtr <WeirdPtr@WeirdPtr.com>"]
description = "CSGOEmpire REST-API and Socket Bindings"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/WeirdPtr/csgoempire-rs"
keywords = ["csgoempire", "api", "websocket"]
include = ["src/**/*", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]
publish = false

[dependencies]
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
